#!/bin/sh
# Backlight notification program for xbacklight.

APPLICATION="notify-backlight"
ICON_LOW="display-brightness-symbolic"
ICON_MID="display-brightness-symbolic"
ICON_HIGH="display-brightness-symbolic"
TMP_NID="/tmp/${APPLICATION}-id"

BRIGHTNESS=$(xbacklight | sed 's/[.][0-9]*//')
if [[ $BRIGHTNESS -le 33 ]]; then
	ICON=$ICON_LOW
elif [[ $BRIGHTNESS -le 66 ]]; then
	ICON=$ICON_MID
else
	ICON=$ICON_HIGH
fi

NID=$(cat $TMP_NID)
if [[ $NID == "" ]]; then
	echo "0" > $TMP_NID; NID=0
fi

DISPLAY=:0
NID=$(/usr/bin/notify-send $APPLICATION -i $ICON -h int:value:$BRIGHTNESS -r $NID -p)
echo "$NID" > $TMP_NID

