#!/bin/sh
# Volume notification program for PulseAudio.

APPLICATION="notify-volume"
ICON_LOW="audio-volume-low-symbolic"
ICON_MID="audio-volume-medium-symbolic"
ICON_HIGH="audio-volume-high-symbolic"
ICON_MUTED="audio-volume-muted-symbolic"
TMP_NID="/tmp/${APPLICATION}-id"

VOLUME=$(pamixer --get-volume)
MUTED=$(pamixer --get-mute)
if [[ $MUTED == "true" ]]; then
	ICON=$ICON_MUTED
elif [[ $VOLUME -le 33 ]]; then
	ICON=$ICON_LOW
elif [[ $VOLUME -le 66 ]]; then
	ICON=$ICON_MID
else
	ICON=$ICON_HIGH
fi

NID=$(cat $TMP_NID)
if [[ $NID == "" ]]; then
	echo 0 > $TMP_NID; NID=0
fi

NID=$(/usr/bin/notify-send $APPLICATION -i $ICON -h int:value:$VOLUME -r $NID -p)
echo $NID > $TMP_NID

