#!/bin/sh
# Rest-your-eyes notification program.
# Run every 20 minutes.

# Only notify if this script was run about 20 minutes ago, so it won't run
# when, for example, cron is trying to catch up after a resume (unless it
# does that about 20 minutes after the last run).

# A cron job should specify the the display to show the notification on and 
# the dbus address to send it to: DISPLAY=... DBUS_SESSION_BUS_ADDRESS=...

APPLICATION="notify-eyes"
ICON="user-not-tracked-symbolic"
TMP_NID="/tmp/${APPLICATION}-id"

NID=$(cat $TMP_NID)
if [[ $NID == "" ]]; then
	echo 0 > $TMP_NID; NID=0
fi

TIME_ELAPSED=`expr $(date +%s) - $(stat -c %Y $TMP_NID)`
if (( $TIME_ELAPSED > 1170 && $TIME_ELAPSED < 1230 )); then
	NID=$(/usr/bin/notify-send $APPLICATION -i $ICON -u CRITICAL -t 0 \
		-r $NID -p "Rest your eyes for a minute.")
fi

echo $NID > $TMP_NID

